"""wisconsincheese.com (Dairy Farmers of Wisconsin) scraper — the consumer layer.

Source
    Server-rendered HTML (Kentico CMS) — requests + BeautifulSoup, no JS needed.
    Verified July 2026:
    - Makers directory:  /our-cheese/our-makers
        "Made By" list (~100 consumer creameries) and "Sold By" list, each
        linking to /wi-cheese-companies/{id}/{slug} — numeric id is the
        company's stable DFW key.
    - Company pages:     /wi-cheese-companies/{id}/{slug}
        Cheese offerings per company, retail flags (store / mail order / online).
    - Cheese finder:     /our-cheese/find-cheese  (per-cheese detail pages)
    - Enumeration aid:   /sitemap-frontend
    - The makers page cheese filter exposes ~150 named cheese types including
      trademarked originals (?cheese={id} — the ids are a type vocabulary).

Output → data/raw/dfw.json
    [
      {
        "source_key": "39",                 # DFW company id — REQUIRED on every record
        "name": "...", "url": "...",
        "city": "...",
        "retail": {"store": true, "mail_order": false, "online": true},
        "cheeses": [
          {"name": "...", "type": "...", "url": "...", "description_raw": "..."}
        ]
      },
      ...
    ]

Rules
    - description_raw is scraped for the tagging pass ONLY. It is marketing
      copy and must never reach build output — reader-facing descriptions are
      generated by scripts/describe.py from structured fields.
    - Be polite: identify with a real User-Agent, throttle requests
      (>= 1s between pages), cache responses locally during development.
    - Fail loudly on structural changes; never emit partial output.
"""
from __future__ import annotations

from pathlib import Path

BASE = "https://www.wisconsincheese.com"
OUTPUT = Path(__file__).resolve().parent.parent / "data" / "raw" / "dfw.json"


def main() -> None:
    raise NotImplementedError("dfw scraper not yet implemented — see module docstring")


if __name__ == "__main__":
    main()
