"""wisconsincheese.com (Dairy Farmers of Wisconsin) scraper — the consumer layer.

Source
    Server-rendered HTML (Kentico CMS) — requests + BeautifulSoup, no JS needed.
    Verified against the live site July 2026:

    - Makers directory:  /our-cheese/our-makers
        Two lists, "Made By:" (94 companies) and "Sold By:" (47), 114 distinct,
        each linking to /wi-cheese-companies/{id}/{slug}; the numeric id is the
        company's stable DFW key. The page also carries the site's entire cheese
        vocabulary in a <select> — 158 types, brand names (BellaVitano®, Alpine
        Renegade) sitting alongside generic ones (Colby, Gouda).

    - Type filter:       /our-cheese/our-makers?cheese={type_id}
        Filtered server-side, and this is the AUTHORITATIVE company ↔ cheese-type
        mapping. The carousel on a company page is a curated subset, NOT a
        complete list: Arena Cheese's page shows only curds/colby/gouda though
        Arena is the home of the original co-jack and ?cheese=16 lists it.

    - Company pages:     /wi-cheese-companies/{id}/{slug}
        Description, "Retail Stores" and "Headquarters" blocks (postal address,
        phone, website), master cheesemakers with their certified varieties,
        lifetime award count, and — usefully — lat/lng for every location,
        pushed into window.companyMapLocations by an inline script.

    - Cheese feed:       /feeds/default.aspx
        The JSON behind /our-cheese/find-cheese: 55 varieties carrying DFW's own
        Hardness / Intensity / Flavors groupings. Written to
        data/raw/dfw_varieties.json as a reference table for the flavor tagging
        pass. build.py does not read it — it holds no source records.

What this source does NOT publish
    - Per-company NAMED PRODUCTS. Company pages list cheese *types* shared
      site-wide ("Gouda"), never "Marieke Gouda Smoked". SCHEMA.md's
      one-record-per-named-product cheese catalog has no source here.
    - Mail-order / online-ordering flags. The makers page offers both as filter
      options, but the server ignores those parameters and no markup anywhere
      carries the values, so they are emitted as null (unknown) and never
      guessed. Only retail.store is observable, from the Retail Stores block.

Output → data/raw/dfw.json
    [
      {
        "source_key": "104",                # DFW company id — REQUIRED on every record
        "name": "Arena Cheese",
        "url": "https://www.wisconsincheese.com/wi-cheese-companies/104/arena-cheese-inc",
        "roles": ["maker"],                 # maker | seller (a company can be both)
        "city": "Arena",                    # from the Headquarters block
        "retail": {"store": true, "mail_order": null, "online": null},
        "website": "http://www.arenacheese.com",
        "phone": "608-753-2501",
        "award_count": 65,
        "description_raw": "...",
        "locations": [
          {"kind": "Retail Stores", "name": "...", "street": "...", "city": "...",
           "state": "WI", "zip": "53503", "phone": "...", "website": "...",
           "lat": 43.161586, "lng": -89.911089}
        ],
        "cheese_types": [{"id": 15, "name": "Colby", "roles": ["made"]}],
        "master_cheesemakers": [{"name": "Bill Hanson", "varieties": ["Colby", "Gouda"]}]
      },
      ...
    ]

Rules
    - description_raw is scraped for the tagging pass ONLY. It is marketing copy
      and must never reach build output — reader-facing descriptions are
      generated by scripts/describe.py from structured fields.
    - Be polite: real User-Agent, >= 1s between pages (enforced in _fetch), and
      CHEESE_CENSUS_CACHE=1 serves from .cache/ while developing.
    - Fail loudly on structural changes; never emit partial output.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from bs4 import BeautifulSoup

from _fetch import collapse, fatal, fetch_text, write_json

SCRAPER = "dfw"
BASE = "https://www.wisconsincheese.com"
MAKERS_URL = f"{BASE}/our-cheese/our-makers"
FEED_URL = f"{BASE}/feeds/default.aspx"

RAW = Path(__file__).resolve().parent.parent / "data" / "raw"
OUTPUT = RAW / "dfw.json"
VARIETIES_OUTPUT = RAW / "dfw_varieties.json"

LIST_HEADINGS = {"Made By:": "maker", "Sold By:": "seller"}
COMPANY_HREF = re.compile(r"^/wi-cheese-companies/(\d+)/")
CITY_STATE_ZIP = re.compile(r"^(?P<city>.+?),\s*(?P<state>[A-Z]{2})\s+(?P<zip>\d{5}(?:-\d{4})?)$")
PHONE_LINE = re.compile(r"^[\d\(\)\.\-\s]{7,}(?:x\s*\d+)?$")
MAP_PUSH = re.compile(r"locations\.push\(\s*\{(?P<body>.*?)\}\s*\)", re.S)
MAP_FIELD = re.compile(r"(?P<key>title|subtitle|address|lat|lng)\s*:\s*(?P<value>\"[^\"]*\"|'[^']*'|-?[\d.]+)")
VARIETY_HREF = re.compile(r"^/cheeses/(\d+)/")

# Sanity floors. These are not tuning knobs — they are the point at which the
# source has changed enough that continuing would emit a quietly wrong dataset.
MIN_COMPANIES = 80
MIN_CHEESE_TYPES = 100


def _soup(html: str) -> BeautifulSoup:
    return BeautifulSoup(html, "html.parser")


def _text(node) -> str:
    return collapse(node.get_text(" ", strip=True))


def parse_company_lists(html: str, *, context: str) -> dict[str, dict]:
    """Read the Made By / Sold By panels into {company_id: {name, href, roles}}."""
    soup = _soup(html)
    found: dict[str, dict] = {}
    seen_headings = set()
    for heading in soup.find_all("h4"):
        label = _text(heading)
        if label not in LIST_HEADINGS:
            continue
        seen_headings.add(label)
        panel = heading.find_next_sibling("div", class_="filter-content")
        if panel is None:
            fatal(SCRAPER, f"{context}: '{label}' heading has no sibling div.filter-content")
        for anchor in panel.select("div.companies-wrapper a[href]"):
            match = COMPANY_HREF.match(anchor["href"])
            if not match:
                fatal(SCRAPER, f"{context}: unparseable company href {anchor['href']!r}")
            record = found.setdefault(
                match.group(1),
                {"name": _text(anchor), "href": anchor["href"], "roles": set()},
            )
            record["roles"].add(LIST_HEADINGS[label])

    missing = set(LIST_HEADINGS) - seen_headings
    if missing:
        fatal(SCRAPER, f"{context}: missing company list heading(s) {sorted(missing)}")
    return found


def parse_cheese_vocabulary(html: str) -> list[tuple[int, str]]:
    """The site's cheese-type vocabulary, from the makers page filter <select>."""
    soup = _soup(html)
    select = soup.find("select", id=re.compile(r"drpCheese$"))
    if select is None:
        fatal(SCRAPER, "makers page: cheese-type <select> (id ending 'drpCheese') not found")

    types: list[tuple[int, str]] = []
    for option in select.find_all("option"):
        value = (option.get("value") or "").strip()
        if not value.isdigit():
            continue  # the '##ALL##' placeholder
        types.append((int(value), _text(option)))

    if len(types) < MIN_CHEESE_TYPES:
        fatal(
            SCRAPER,
            f"makers page: cheese vocabulary has {len(types)} types, expected at least "
            f"{MIN_CHEESE_TYPES} — the filter markup has changed",
        )
    return types


def _parse_map_locations(module) -> list[dict]:
    coordinates: list[dict] = []
    for script in module.find_all("script"):
        for push in MAP_PUSH.finditer(script.get_text()):
            fields = {
                m.group("key"): m.group("value").strip("\"'")
                for m in MAP_FIELD.finditer(push.group("body"))
            }
            if "lat" not in fields or "lng" not in fields:
                fatal(SCRAPER, f"map location without lat/lng: {push.group('body')[:120]!r}")
            coordinates.append({
                "subtitle": collapse(fields.get("subtitle", "")) or None,
                "lat": float(fields["lat"]),
                "lng": float(fields["lng"]),
            })
    return coordinates


def _parse_information(block, *, kind: str, company_id: str) -> dict:
    lines = [_text(div) for div in block.find_all("div", recursive=False)]
    lines = [line for line in lines if line]

    city_line = next((i for i, line in enumerate(lines) if CITY_STATE_ZIP.match(line)), None)
    if city_line is None:
        fatal(
            SCRAPER,
            f"company {company_id}: '{kind}' block has no 'City, ST ZIP' line — "
            f"address markup has changed. Lines: {lines}",
        )
    place = CITY_STATE_ZIP.match(lines[city_line])

    website = None
    for anchor in block.find_all("a", href=True):
        if "visit website" in _text(anchor).lower():
            website = anchor["href"].strip()
    phone = next((line for line in lines[city_line + 1:] if PHONE_LINE.match(line)), None)

    return {
        "kind": kind,
        "name": lines[0] if city_line > 0 else None,
        "street": " ".join(lines[1:city_line]) or None,
        "city": place.group("city"),
        "state": place.group("state"),
        "zip": place.group("zip"),
        "phone": phone,
        "website": website,
    }


def parse_company_page(html: str, *, company_id: str, url: str) -> dict:
    soup = _soup(html)

    heading = soup.find("h1")
    if heading is None:
        fatal(SCRAPER, f"company {company_id}: no <h1> — page markup has changed")

    locations: list[dict] = []
    for module in soup.select("div.company-info-module"):
        label = module.find("h3")
        kind = _text(label) if label else None
        if not kind:
            fatal(SCRAPER, f"company {company_id}: company-info-module without an <h3> label")
        blocks = module.select("div.information")
        coordinates = _parse_map_locations(module)
        if len(blocks) != len(coordinates):
            fatal(
                SCRAPER,
                f"company {company_id}: '{kind}' has {len(blocks)} address block(s) but "
                f"{len(coordinates)} map location(s) — cannot pair them reliably",
            )
        for block, point in zip(blocks, coordinates):
            locations.append({
                **_parse_information(block, kind=kind, company_id=company_id),
                "lat": point["lat"],
                "lng": point["lng"],
            })

    headquarters = next((l for l in locations if l["kind"] == "Headquarters"), None)
    primary = headquarters or (locations[0] if locations else None)

    makers = []
    for item in soup.select("div.cheese-maker-item"):
        name = item.find("h4")
        if name is None:
            continue
        varieties = [
            _text(a) for a in item.find_all("a", href=True)
            if VARIETY_HREF.match(a["href"])
        ]
        makers.append({"name": _text(name), "varieties": varieties})

    award = soup.select_one("div.award__number")
    description = soup.select_one("div.details div.margined-col")
    carousel = [
        _text(item.find("h4"))
        for item in soup.select("div.carousel-item[data-url]")
        if item.find("h4")
    ]

    return {
        "source_key": company_id,
        "name": _text(heading),
        "url": url,
        "city": primary["city"] if primary else None,
        "retail": {
            "store": any(l["kind"] == "Retail Stores" for l in locations),
            "mail_order": None,
            "online": None,
        },
        "website": primary["website"] if primary else None,
        "phone": primary["phone"] if primary else None,
        "award_count": int(_text(award)) if award and _text(award).isdigit() else None,
        "description_raw": _text(description) if description else None,
        "locations": locations,
        "featured_cheeses": carousel,
        "master_cheesemakers": makers,
    }


def parse_varieties(payload: str) -> list[dict]:
    """The find-cheese feed: varieties plus DFW's hardness/intensity/flavor groupings."""
    try:
        feed = json.loads(payload)
    except json.JSONDecodeError as error:
        fatal(SCRAPER, f"{FEED_URL} did not return JSON: {error}")

    for key in ("Cheeses", "Hardness", "Intensity", "Flavors"):
        if key not in feed:
            fatal(SCRAPER, f"cheese feed is missing the '{key}' key — feed shape has changed")

    groupings: dict[int, dict[str, list[str]]] = {}
    for group, id_key in (("Hardness", "hardnessId"), ("Intensity", "intensityId"), ("Flavors", "flavorId")):
        for entry in feed[group]:
            if id_key not in entry or "cheeseIds" not in entry:
                fatal(SCRAPER, f"cheese feed '{group}' entry lacks {id_key}/cheeseIds: {entry}")
            for cheese_id in entry["cheeseIds"]:
                groupings.setdefault(cheese_id, {}).setdefault(group.lower(), []).append(entry["name"])

    varieties = []
    for cheese in feed["Cheeses"]:
        tags = groupings.get(cheese["uid"], {})
        varieties.append({
            "id": cheese["uid"],
            "name": collapse(cheese["name"]),
            "description_raw": collapse(cheese.get("description") or "") or None,
            "hardness": sorted(tags.get("hardness", [])),
            "intensity": sorted(tags.get("intensity", [])),
            "flavors": sorted(tags.get("flavors", [])),
        })
    varieties.sort(key=lambda v: v["id"])
    return varieties


def main() -> None:
    makers_html = fetch_text(MAKERS_URL, scraper=SCRAPER)
    companies = parse_company_lists(makers_html, context="makers page")
    if len(companies) < MIN_COMPANIES:
        fatal(
            SCRAPER,
            f"makers page listed {len(companies)} companies, expected at least "
            f"{MIN_COMPANIES} — the directory markup has changed",
        )
    cheese_types = parse_cheese_vocabulary(makers_html)
    print(f"dfw: {len(companies)} companies, {len(cheese_types)} cheese types in the vocabulary")

    # Authoritative company <-> cheese-type mapping, one filtered page per type.
    mapping: dict[str, dict[int, dict]] = {}
    for index, (type_id, type_name) in enumerate(cheese_types, start=1):
        filtered = fetch_text(f"{MAKERS_URL}?cheese={type_id}", scraper=SCRAPER)
        for company_id, record in parse_company_lists(
            filtered, context=f"?cheese={type_id}"
        ).items():
            if company_id not in companies:
                fatal(
                    SCRAPER,
                    f"?cheese={type_id} lists company {company_id} that is absent from the "
                    f"unfiltered makers page — the directory is inconsistent",
                )
            entry = mapping.setdefault(company_id, {}).setdefault(
                type_id, {"id": type_id, "name": type_name, "roles": set()}
            )
            entry["roles"].update(
                "made" if role == "maker" else "sold" for role in record["roles"]
            )
        if index % 25 == 0 or index == len(cheese_types):
            print(f"dfw:   cheese-type sweep {index}/{len(cheese_types)}")

    records = []
    for position, (company_id, listing) in enumerate(sorted(companies.items(), key=lambda kv: int(kv[0])), start=1):
        url = BASE + listing["href"]
        record = parse_company_page(
            fetch_text(url, scraper=SCRAPER), company_id=company_id, url=url
        )
        record["roles"] = sorted(listing["roles"])
        record["cheese_types"] = [
            {"id": t["id"], "name": t["name"], "roles": sorted(t["roles"])}
            for t in sorted(mapping.get(company_id, {}).values(), key=lambda t: t["id"])
        ]
        records.append(record)
        if position % 25 == 0 or position == len(companies):
            print(f"dfw:   company pages {position}/{len(companies)}")

    records.sort(key=lambda r: int(r["source_key"]))
    write_json(OUTPUT, records)

    varieties = parse_varieties(fetch_text(FEED_URL, scraper=SCRAPER))
    write_json(VARIETIES_OUTPUT, varieties)

    with_types = sum(1 for r in records if r["cheese_types"])
    with_coords = sum(1 for r in records if r["locations"])
    print(
        f"dfw: {len(records)} companies ({with_types} with cheese types, "
        f"{with_coords} with coordinates) -> data/raw/dfw.json; "
        f"{len(varieties)} varieties -> data/raw/dfw_varieties.json"
    )


if __name__ == "__main__":
    main()
